
version: 0.2

phases:
  build:
    commands:
      - mvn clean package

  post_build:
    commands:
      - mvn package
      - mv target/my-web-app-0.war my-web-app.war
artifacts:
  files:
    - my-web-app.war
    - .ebextensions/**/*
